import { CAPABILITIES, escapeHtml, has, state, trDate, trMoney } from "./state.js";

export function renderLedger() {
  const supplierId = String(state.filters.ledgerSupplier || "");
  const entries = state.ledgerEntries.filter((entry) => !supplierId || entry.supplierId === supplierId);
  const balance = entries.reduce((sum, entry) => sum + Number(entry.amountKurus || 0), 0);
  const debt = entries.filter((entry) => Number(entry.amountKurus) < 0).reduce((sum, entry) => sum + Math.abs(entry.amountKurus), 0);
  const payment = entries.filter((entry) => Number(entry.amountKurus) > 0).reduce((sum, entry) => sum + entry.amountKurus, 0);
  return `<div class="section-toolbar"><div class="filters"><select class="toolbar-control" id="ledger-supplier"><option value="">Tüm tedarikçiler</option>${state.suppliers.map((item) => `<option value="${escapeHtml(item.id)}" ${supplierId === item.id ? "selected" : ""}>${escapeHtml(item.name)}</option>`).join("")}</select></div><div class="toolbar-actions"><a class="ui-button ui-button--secondary" href="/api/procurement/v1/export?kind=ledger" download>Excel uyumlu çıktı</a>${has(CAPABILITIES.paymentCreate) ? '<button class="ui-button ui-button--primary" data-action="new-payment">Ödeme gir</button>' : ""}${has(CAPABILITIES.accountingPost) ? '<button class="ui-button ui-button--secondary" data-action="new-ledger-entry">Bağımsız hareket</button>' : ""}</div></div>
    <div class="metric-grid"><article class="metric-card"><span>Toplam borç hareketi</span><strong>${trMoney(debt)}</strong><small>Fatura ve borçlar negatif işaretle saklanır.</small></article><article class="metric-card"><span>Toplam ödeme/alacak</span><strong>${trMoney(payment)}</strong><small>Ödemeler pozitif işaretle saklanır.</small></article><article class="metric-card ${balance < 0 ? "is-danger" : ""}"><span>Kalan bakiye</span><strong>${trMoney(Math.abs(balance))}</strong><small>${balance < 0 ? "Tedarikçiye borç" : "Alacak / kapalı bakiye"}</small></article><article class="metric-card"><span>Hareket sayısı</span><strong>${entries.length}</strong><small>Geçmiş kayıtlar silinmez.</small></article></div>
    ${entries.length ? `<article class="panel-card table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Tarih</th><th>Tedarikçi</th><th>Tür</th><th>Açıklama</th><th class="right">Borç</th><th class="right">Ödeme</th><th class="right">Koşan bakiye</th><th>Vade</th><th></th></tr></thead><tbody>${entries.map(ledgerRow).join("")}</tbody></table></div></article>` : empty("Cari hareket yok", "Muhasebeleştirilen belge veya ödeme henüz bulunmuyor.")}`;
}

export function paymentFormBody() {
  return `<div class="form-grid"><label>Tedarikçi<select name="supplierId" required><option value="">Seçin</option>${state.suppliers.filter((item) => item.active !== false).map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join("")}</select></label><label>Ödeme tutarı (₺)<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Ödeme tarihi<input name="paymentDate" type="date" value="${today()}" required></label><label>Referans<input name="reference" maxlength="120" placeholder="Dekont / kasa referansı"></label><label class="span-2">Not<textarea name="note" maxlength="1000"></textarea></label></div><p class="result-meta" style="margin-top:12px">Ödeme stok miktarını değiştirmez; cari deftere pozitif hareket olarak eklenir.</p>`;
}

export function ledgerEntryFormBody() {
  return `<div class="form-grid"><label>Tedarikçi<select name="supplierId" required><option value="">Seçin</option>${state.suppliers.map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join("")}</select></label><label>Hareket türü<select name="type" required><option value="opening_balance">Açılış bakiyesi</option><option value="adjustment">Düzeltme</option><option value="credit_note">Alacak dekontu</option></select></label><label>Tutar (₺)<input name="amount" type="number" min="0.01" step="0.01" required></label><label>İşaret<select name="direction"><option value="debt">Borç (negatif)</option><option value="credit">Alacak (pozitif)</option></select></label><label>Vade<input name="dueDate" type="date"></label><label>Kaynak referansı<input name="sourceId" maxlength="180"></label><label class="span-2">Not<textarea name="note" maxlength="1000" required></textarea></label></div>`;
}

export function renderUsers() {
  return `${state.users.length ? `<div class="card-grid">${state.users.map(userCard).join("")}</div>` : empty("Personel hesabı yok", "Yetki ataması mevcut personel hesapları üzerinde yapılır.")}`;
}

export function userAccessFormBody(user) {
  const capabilities = [
    [CAPABILITIES.read,"Genel bakış"],[CAPABILITIES.supplierRead,"Tedarikçi okuma"],[CAPABILITIES.supplierManage,"Tedarikçi yönetimi"],[CAPABILITIES.links,"Ürün eşleştirme"],
    [CAPABILITIES.receiptCreate,"Mal kabul oluşturma"],[CAPABILITIES.receiptSubmit,"Mal kabul gönderme"],[CAPABILITIES.receiptApprove,"Stok onayı"],[CAPABILITIES.receiptReject,"Sevkiyat reddi"],
    [CAPABILITIES.accountingRead,"Cari hesap okuma"],[CAPABILITIES.accountingPost,"Muhasebeleştirme"],[CAPABILITIES.accountingReverse,"Muhasebe ters kaydı"],[CAPABILITIES.paymentCreate,"Ödeme kaydı"],[CAPABILITIES.paymentReverse,"Ödeme ters kaydı"],
    [CAPABILITIES.documentsRead,"Belge okuma"],[CAPABILITIES.documentsUpload,"Belge yükleme"],[CAPABILITIES.documentsArchive,"Belge arşivleme"],[CAPABILITIES.users,"Kullanıcı ve yetki yönetimi"]
  ];
  const current = Array.isArray(user.faturaCapabilities) ? user.faturaCapabilities : [];
  const fallbackTemplates = [
    {key:"mal_kabul",label:"Mal Kabul Personeli",role:"mal_kabul",capabilities:[CAPABILITIES.supplierRead,CAPABILITIES.receiptCreate,CAPABILITIES.receiptSubmit,CAPABILITIES.receiptApprove,CAPABILITIES.receiptReject,CAPABILITIES.documentsRead,CAPABILITIES.documentsUpload]},
    {key:"satin_alma",label:"Satın Alma",role:"satın_alma",capabilities:[CAPABILITIES.read,CAPABILITIES.supplierRead,CAPABILITIES.supplierManage,CAPABILITIES.links,CAPABILITIES.receiptCreate,CAPABILITIES.receiptSubmit,CAPABILITIES.documentsRead,CAPABILITIES.documentsUpload]},
    {key:"muhasebe",label:"Muhasebe",role:"muhasebe",capabilities:[CAPABILITIES.supplierRead,CAPABILITIES.documentsRead,CAPABILITIES.accountingRead,CAPABILITIES.accountingPost,CAPABILITIES.accountingReverse,CAPABILITIES.paymentCreate,CAPABILITIES.paymentReverse]},
    {key:"yonetici",label:"Fatura Yöneticisi",role:"yönetici",capabilities:capabilities.map(([key])=>key)},
    {key:"ozel",label:"Özel Yetki",role:"özel",capabilities:[]}
  ];
  const templates = state.accessTemplates.length ? state.accessTemplates : fallbackTemplates;
  const inferred = templates.find((template) => template.role === user.faturaRole && sameCapabilities(current, template.capabilities))?.key || "ozel";
  const currentKey = String(user.faturaTemplate || inferred);
  const enabled = user.faturaAccessEnabled !== false && current.length > 0;
  const custom = currentKey === "ozel";
  return `<div class="form-grid"><label class="check-field span-2 access-toggle"><input type="checkbox" name="faturaAccess" ${enabled ? "checked" : ""}><span>Bu personel Tahmisçi Fatura uygulamasına erişebilsin</span></label><label>Hazır yetki şablonu<select id="access-template" name="accessTemplate">${templates.map((template) => `<option value="${escapeHtml(template.key)}" data-role="${escapeHtml(template.role)}" data-capabilities="${escapeHtml((template.capabilities || []).join(","))}" ${currentKey === template.key ? "selected" : ""}>${escapeHtml(template.label)}</option>`).join("")}</select></label><label>Fatura rolü<select id="fatura-role" name="faturaRole"><option value="özel" ${user.faturaRole === "özel" ? "selected" : ""}>Özel</option><option value="operasyon" ${user.faturaRole === "operasyon" ? "selected" : ""}>Operasyon</option><option value="mal_kabul" ${user.faturaRole === "mal_kabul" ? "selected" : ""}>Mal kabul</option><option value="muhasebe" ${user.faturaRole === "muhasebe" ? "selected" : ""}>Muhasebe</option><option value="satın_alma" ${user.faturaRole === "satın_alma" ? "selected" : ""}>Satın alma</option><option value="yönetici" ${user.faturaRole === "yönetici" ? "selected" : ""}>Yönetici</option></select></label></div><p class="result-meta permission-help">Şablon seçebilir veya Özel Yetki ile bölüm ve işlemleri tek tek belirleyebilirsiniz. Menü görünürlüğü ve API erişimi aynı capability kaydından yönetilir.</p><div class="permission-grid" data-access-controls>${capabilities.map(([key,label]) => `<label class="check-field"><input type="checkbox" name="capabilities" value="${key}" ${current.includes(key) ? "checked" : ""} ${enabled && custom ? "" : "disabled"}><span>${escapeHtml(label)}</span></label>`).join("")}</div>`;
}

export function renderSettingsAudit() {
  const settings = state.settings || {};
  return `<div class="content-grid"><article class="panel-card"><div class="panel-head"><div><h2>Tahmisçi Fatura ayarları</h2><p>Birim sözlüğü ve muhasebe belge türleri</p></div></div><div style="padding:0 16px 16px"><form id="settingsForm"><div class="form-grid"><label>Yaklaşan vade (gün)<input name="dueSoonDays" type="number" min="1" max="90" value="${Number(settings.dueSoonDays || 7)}" ${has(CAPABILITIES.users) ? "" : "disabled"}></label><label>Para birimi<input value="TRY" disabled></label><label class="span-2">Birimler (virgülle)<textarea name="units" ${has(CAPABILITIES.users) ? "" : "disabled"}>${escapeHtml((settings.units || []).join(", "))}</textarea></label><label class="span-2">Muhasebeleştirilebilir belge türleri<input value="${escapeHtml((settings.accountingDocumentTypes || []).join(", "))}" disabled></label></div>${has(CAPABILITIES.users) ? '<button class="ui-button ui-button--primary" type="submit" style="margin-top:12px">Ayarları kaydet</button>' : ""}</form></div></article><article class="panel-card"><div class="panel-head"><div><h2>Audit özeti</h2><p>Son kalıcı işlemler</p></div></div><div class="list">${state.auditEvents.slice(0,15).map((event) => `<div class="list-row"><div class="list-main"><strong>${escapeHtml(event.operation || event.type || "İşlem")}</strong><span>${escapeHtml(event.actorName || event.actorId || "Sistem")} · ${trDate(event.createdAt, true)}</span></div><span class="badge is-muted">r${Number(event.revision || 0)}</span></div>`).join("") || '<div class="list-row"><div class="list-main"><span>Audit kaydı yok.</span></div></div>'}</div></article></div>`;
}

function ledgerRow(entry) {
  const supplier = state.suppliers.find((item) => item.id === entry.supplierId);
  const isDebt = Number(entry.amountKurus || 0) < 0;
  const reversible = !entry.reversalOf && !state.ledgerEntries.some((item) => item.reversalOf === entry.id);
  return `<tr><td data-label="Tarih">${trDate(entry.createdAt, true)}</td><td data-label="Tedarikçi">${escapeHtml(supplier && supplier.name || entry.supplierId)}</td><td data-label="Tür">${escapeHtml(typeLabel(entry.type))}</td><td data-label="Açıklama">${escapeHtml(entry.note || entry.sourceType || "—")}</td><td data-label="Borç" class="right">${isDebt ? trMoney(Math.abs(entry.amountKurus)) : "—"}</td><td data-label="Ödeme" class="right">${!isDebt ? trMoney(entry.amountKurus) : "—"}</td><td data-label="Koşan bakiye" class="right">${trMoney(Math.abs(entry.runningBalanceKurus || 0))}</td><td data-label="Vade">${trDate(entry.dueDate)}</td><td class="actions">${reversible && has(CAPABILITIES.accountingReverse) ? `<button class="row-button danger" data-reverse-ledger="${escapeHtml(entry.id)}">Ters kayıt</button>` : ""}</td></tr>`;
}
function userCard(user) { const access=user.faturaAccessEnabled!==false&&(user.faturaCapabilities||[]).length>0;const template=state.accessTemplates.find((item)=>item.key===user.faturaTemplate);return `<article class="entity-card"><div class="entity-footer" style="margin-top:0"><h3>${escapeHtml(user.name)}</h3><span class="badge ${access ? "is-success" : "is-muted"}">${access ? "Fatura açık" : "Fatura kapalı"}</span></div><p>@${escapeHtml(user.username)} · ${escapeHtml(user.faturaRole || "operasyon")}</p><div class="entity-meta"><div><span>Şube</span><strong>${escapeHtml(user.branchId || "main")}</strong></div><div><span>Şablon</span><strong>${escapeHtml(template&&template.label||user.faturaTemplate||"Özel Yetki")}</strong></div><div><span>Görünen bölüm</span><strong>${(user.faturaSections||[]).length}</strong></div><div><span>İşlem yetkisi</span><strong>${(user.faturaCapabilities||[]).length}</strong></div></div><div class="entity-footer"><span></span><button class="row-button" data-edit-user="${escapeHtml(user.id)}">Yetkileri düzenle</button></div></article>`; }
function sameCapabilities(first, second){const a=[...new Set(first || [])].sort();const b=[...new Set(second || [])].sort();return a.length===b.length&&a.every((item,index)=>item===b[index])}
function typeLabel(value){return ({invoice:"Fatura / borç",payment:"Ödeme",credit_note:"Alacak dekontu",reversal:"Ters kayıt",opening_balance:"Açılış bakiyesi",adjustment:"Düzeltme"})[value]||value}
function today(){return new Date().toISOString().slice(0,10)}
function empty(title, copy) { return `<div class="empty-state"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(copy)}</p></div></div>`; }
